http:
  routers:
    to-whoami:
      # rule: "Host(`k12345678s.top`) && PathPrefix(`/`)"
      rule: "Host(`k12345678s.top`) && PathPrefix(`/`)"

      # middlewares:
      # - test-user
      service: whoami

  # middlewares:
  #   test-user:
  #     basicAuth:
  #       users:
  #       - liu:$apr1$1r/b.LIT$8lNAPTWChn/1xz9Q8nTKQ.

  services:
    whoami:
      loadBalancer:
        servers:
        
        # - url : http://k12345678s.top:8080/dashboard/#/
        - url: "http://10.128.63.28:30090/"
          # - url: "http://www.baidu.com:30090"
            



    # to-whoami1:
    #   rule: "PathPrefix(`/logistics`)"
    #   servers: testservice


      # middlewares:
      # - test-user
      # service: whoami


  #     basicAuth:
  #       users:
  #       - liu:$apr1$1r/b.LIT$8lNAPTWChn/1xz9Q8nTKQ.

  # services:
  #   testservice:
  #     loadBalancer:
  #       servers:
  #       # - url: http://hw485.andrewlu.cn/logistics/
  #         -url: "http://hw485.andrewlu.cn/logistics/"
    