http:
  routers:

    to-whoami:
      # rule: "PathPrefix(`/v`) "
      rule: "PathPrefix(`/*`)"
      # rule: "Host(`k12345678s.top`) && PathPrefix(`/logistics`)"
      service: whoami

    to-whoami12:
      rule: "PathPrefix(`/logistics/`)"
      service: whoami1



  services:
    whoami:
      loadBalancer:
        servers:
        # - url: "http://10.128.63.28:30090/"
        - url: http://www.bilibili.com/
        # - url: "http://hw485.andrewlu.cn/logistics"
          
  # services:
    whoami1:
      loadBalancer:
        servers:
        # - url: "http://10.128.63.28:30090/"
        # - url: "http://hw485.andrewlu.cn/logistics/"
        - url: https://www.baidu.com/

          
  # servers:
  #   whoami1:
  #     loadBalancer:
  #       servers:
  #       # - url: "http://10.128.63.28:30090/"
  #       - url: "http://hw485.andrewlu.cn/logistics"